<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RobotStudio.Domain\RobotStudio.Domain.csproj" />
    <ProjectReference Include="..\RobotStudio.Scripting\RobotStudio.Scripting.csproj" />
    <ProjectReference Include="..\RobotStudio.Simulation\RobotStudio.Simulation.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
