using System.Text;
using RobotStudio.Domain;
using RobotStudio.Domain.Cartesian;
using RobotStudio.Domain.Commands;
using RobotStudio.Motion;
using RobotStudio.Simulation;

namespace RobotStudio.Desktop.Didactics;

public sealed class CartesianMovementExplanationBuilder
{
    public string Create(
        CartesianRobotProfile profile,
        CartesianPlaybackSnapshot snapshot,
        int frameIndex)
    {
        ArgumentNullException.ThrowIfNull(profile);
        ArgumentNullException.ThrowIfNull(snapshot);

        if (frameIndex < 0 || frameIndex >= snapshot.SceneFrameCount)
        {
            throw new ArgumentOutOfRangeException(nameof(frameIndex));
        }

        var sceneFrame = snapshot.SceneFrames[frameIndex];
        if (sceneFrame.CommandSource is null)
        {
            return "This frame was generated by the simulator before a script command started.";
        }

        var explanation = new StringBuilder();
        explanation.AppendLine($"Command line {sceneFrame.CommandSource.LineNumber}: {sceneFrame.CommandSource.Text}");
        explanation.AppendLine($"Current state: {sceneFrame.State}.");

        switch (sceneFrame.CommandName)
        {
            case nameof(MoveToCommand):
                AppendMotionExplanation(explanation, profile, snapshot, sceneFrame, frameIndex);
                break;

            case nameof(HomeCommand):
                explanation.AppendLine("HOME requests a return to the Cartesian origin at X=0, Y=0, Z=0.");
                AppendMotionExplanation(explanation, profile, snapshot, sceneFrame, frameIndex);
                break;

            case nameof(WaitCommand):
                explanation.AppendLine($"WAIT keeps the current position fixed for {sceneFrame.RequestedWaitDuration?.TotalMilliseconds ?? 0:0.###} ms.");
                explanation.AppendLine("Only simulated time advances while the robot is waiting.");
                break;

            default:
                explanation.AppendLine("This command type is not recognized by the explanation panel yet.");
                break;
        }

        return explanation.ToString().TrimEnd();
    }

    private static void AppendMotionExplanation(
        StringBuilder explanation,
        CartesianRobotProfile profile,
        CartesianPlaybackSnapshot snapshot,
        CartesianSceneFrame sceneFrame,
        int frameIndex)
    {
        var motion = snapshot.CommandMotions?.SingleOrDefault(
            candidate => candidate.CommandIndex == sceneFrame.CommandIndex);
        if (motion is null)
        {
            explanation.AppendLine("Exact motion-profile details are unavailable in this legacy playback snapshot.");
            return;
        }

        if (motion.ProfileShape == MotionProfileShape.Stationary)
        {
            explanation.AppendLine("The target equals the command start position, so no movement phases or simulated time are added.");
            return;
        }

        var limitingVelocityAxis = motion.InvolvedAxes
            .Select(profile.GetAxis)
            .OrderBy(axis => axis.MaximumVelocityMillimetersPerSecond)
            .First();
        var limitingAccelerationAxis = motion.InvolvedAxes
            .Select(profile.GetAxis)
            .OrderBy(axis => axis.MaximumAccelerationMillimetersPerSecondSquared)
            .First();

        explanation.AppendLine($"Involved axes: {string.Join(", ", motion.InvolvedAxes)}.");
        explanation.AppendLine($"Linear distance: {motion.DistanceMillimeters:0.###} mm; planned duration: {motion.TotalDuration.TotalSeconds:0.###} s.");

        if (motion.RequestedVelocityMillimetersPerSecond is { } requestedVelocity)
        {
            explanation.AppendLine($"Requested velocity: {requestedVelocity:0.###} mm/s.");
            explanation.AppendLine(requestedVelocity > motion.VelocityLimitMillimetersPerSecond
                ? $"The request is capped at {motion.VelocityLimitMillimetersPerSecond:0.###} mm/s by the {limitingVelocityAxis.Id} axis."
                : "The requested velocity is within every involved axis limit.");
        }
        else
        {
            explanation.AppendLine($"No velocity was requested, so the {limitingVelocityAxis.Id} axis limit sets a maximum of {motion.VelocityLimitMillimetersPerSecond:0.###} mm/s.");
        }

        explanation.AppendLine($"Peak effective velocity: {motion.PeakVelocityMillimetersPerSecond:0.###} mm/s.");
        explanation.AppendLine($"Acceleration is limited to {motion.AccelerationMillimetersPerSecondSquared:0.###} mm/s^2 by the {limitingAccelerationAxis.Id} axis.");

        if (motion.ProfileShape == MotionProfileShape.Triangular)
        {
            explanation.AppendLine("Profile: triangular. The move is too short to reach the velocity limit, so acceleration changes directly into deceleration.");
        }
        else
        {
            explanation.AppendLine("Profile: trapezoidal. The robot accelerates, cruises at constant velocity, and then decelerates.");
        }

        explanation.AppendLine(
            $"Phase durations: acceleration {motion.AccelerationDuration.TotalSeconds:0.###} s, " +
            $"cruise {motion.ConstantVelocityDuration.TotalSeconds:0.###} s, " +
            $"deceleration {motion.DecelerationDuration.TotalSeconds:0.###} s.");

        var frame = snapshot.Frames[frameIndex];
        explanation.AppendLine(CreateCurrentPhaseExplanation(frame));
    }

    private static string CreateCurrentPhaseExplanation(RobotVisualState frame) =>
        frame.MotionProfilePhase switch
        {
            MotionProfilePhase.Acceleration =>
                $"Current phase: acceleration at {frame.AccelerationMillimetersPerSecondSquared:0.###} mm/s^2; velocity is {frame.VelocityMillimetersPerSecond:0.###} mm/s.",
            MotionProfilePhase.ConstantVelocity =>
                $"Current phase: constant-velocity cruise at {frame.VelocityMillimetersPerSecond:0.###} mm/s.",
            MotionProfilePhase.Deceleration =>
                $"Current phase: deceleration at {Math.Abs(frame.AccelerationMillimetersPerSecondSquared):0.###} mm/s^2; velocity is {frame.VelocityMillimetersPerSecond:0.###} mm/s.",
            MotionProfilePhase.Completed => "Current phase: completed; velocity and acceleration are zero.",
            _ => "Current phase information is unavailable for this frame."
        };
}
