namespace RobotStudio.Desktop.Didactics;

public static class DidacticTooltipCatalog
{
    public const string AxisLimits =
        "Axis limits are the physical minimum and maximum positions the robot is allowed to reach.";

    public const string EffectiveVelocity =
        "Effective velocity is the movement speed actually used after the simulator applies robot limits.";

    public const string Acceleration =
        "Acceleration describes how quickly velocity changes. Negative acceleration indicates deceleration.";

    public const string Homing =
        "Homing moves the robot to a known reference position so later movements start from a predictable place.";

    public const string Playback =
        "Playback replays deterministic simulation frames. It does not execute commands on real hardware.";

    public const string MotionProfile =
        "The motion profile identifies whether the robot is accelerating, moving at constant velocity, decelerating, or has completed the movement.";

    public const string PlannedPath =
        "The planned path shows sampled tool center point positions generated by the simulator.";

    public const string RequestedVelocity =
        "Requested velocity comes from the command. The robot may cap it when an involved axis is slower.";

    public const string RobotState =
        "Robot state describes what the simulator is doing now, such as moving, homing, waiting, completed, or faulted.";

    public const string Timeline =
        "The timeline is a sequence of fixed simulation frames used to inspect command execution over time.";

    public const string ToolCenterPoint =
        "The tool center point, or TCP, is the point on the tool whose position is tracked by the simulator.";

    public const string Workspace =
        "The workspace is the reachable physical region defined by the robot axis limits.";
}
